# Generated by Django 5.2.3 on 2025-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Titre (Français)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Titre (Anglais)')),
                ('content_fr', models.TextField(verbose_name='Contenu (Français)')),
                ('content_en', models.TextField(verbose_name='Contenu (Anglais)')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('author', models.CharField(max_length=100, verbose_name='Auteur')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name="Image de l'article")),
            ],
            options={
                'verbose_name': 'Article de blog/Actualité',
                'verbose_name_plural': 'Articles de blog/Actualités',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
            ],
            options={
                'verbose_name': 'Soumission de contact',
                'verbose_name_plural': 'Soumissions de contact',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre (Français)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre (Anglais)')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10, verbose_name='Type de média')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Fichier image')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Lien vidéo (YouTube, Vimeo, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Élément de galerie',
                'verbose_name_plural': 'Éléments de galerie',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_fr', models.TextField(verbose_name='À propos de nous (Français)')),
                ('about_us_en', models.TextField(verbose_name='À propos de nous (Anglais)')),
                ('vision_fr', models.TextField(verbose_name='Notre vision (Français)')),
                ('vision_en', models.TextField(verbose_name='Notre vision (Anglais)')),
                ('mission_fr', models.TextField(verbose_name='Notre mission (Français)')),
                ('mission_en', models.TextField(verbose_name='Notre mission (Anglais)')),
                ('values_fr', models.TextField(verbose_name='Nos valeurs (Français)')),
                ('values_en', models.TextField(verbose_name='Nos valeurs (Anglais)')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Numéro de téléphone')),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn')),
                ('google_maps_embed_url', models.URLField(blank=True, null=True, verbose_name="Lien d'intégration Google Maps")),
            ],
            options={
                'verbose_name': "Informations sur l'organisation",
                'verbose_name_plural': "Informations sur l'organisation",
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(upload_to='partner_logos/', verbose_name='Logo du partenaire')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Lien du site web')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description (Français)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (Anglais)')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (Français)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titre (Anglais)')),
                ('description_fr', models.TextField(verbose_name='Description (Français)')),
                ('description_en', models.TextField(verbose_name='Description (Anglais)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date du projet/événement')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Lien du projet')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Image du projet')),
                ('is_current', models.BooleanField(default=True, verbose_name='Projet actuel')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (Français)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titre (Anglais)')),
                ('description_fr', models.TextField(verbose_name='Description (Français)')),
                ('description_en', models.TextField(verbose_name='Description (Anglais)')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icône (ex: icon-class or SVG path)')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title_fr'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('title', models.CharField(max_length=200, verbose_name='Titre/Rôle')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/', verbose_name='Photo')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['name'],
            },
        ),
    ]
